services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sattrack_out:/tmp/sattrack_out

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  sattrack_out: